#! /bin/bash
touch database.sqlite
sqlite3 database.sqlite < construct.sql
sqlite3 database.sqlite "insert into api_keys values ('e602f929e7a31b2c7ec1f5c7a9ddd927');"

touch test_db.sqlite
sqlite3 test_db.sqlite < construct.sql
sqlite3 test_db.sqlite "insert into api_keys values ('valid_key');"
